#cloud-config

hostname: hither

coreos:
  update:
    reboot-strategy: best-effort

  units:
    - name: hither.service
      command: start
      content: |
        [Unit]
        Description=Hither container
        After=docker.service

        [Service]
        Restart=always
        ExecStart=/opt/hither/run-hither
        ExecStop=/usr/bin/docker stop -t 5 hither

        [Install]
        WantedBy=local.target

write_files:
  - path: /opt/hither/run-hither
    permissions: 0755
    content: |
      #!/bin/bash
      /usr/bin/docker start -a hither || /usr/bin/docker run --env-file=/opt/hither/env -p 80:9000 -v /opt/hither/localRegistry:/opt/hither/localRegistry --name hither wiredthing/hither:latest

  - path: /opt/hither/env
    permissions: 0755
    content: |
      REGISTRY_INDEX=/opt/hither/localRegistry/index
      REGISTRY_ROOT=/opt/hither/localRegistry/registry
      REGISTRY_CACHE=/opt/hither/localRegistry/cache
      pidfile.path=/dev/null
